name: Spotify Top Artists ETL

on:
  schedule:
    - cron: "0 6 * * *"    # runs daily at 6:00 UTC
  workflow_dispatch:       # allows manual trigger
  push:
    branches: [ main ]     # runs on push too

jobs:
  etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ETL/requirements.txt

      # Sanity check step (verifies secrets exist)
      - name: Sanity check secrets presence
        run: |
          echo "SPOTIFY_CLIENT_ID set?      ${{ secrets.SPOTIFY_CLIENT_ID != '' }}"
          echo "SPOTIFY_CLIENT_SECRET set?  ${{ secrets.SPOTIFY_CLIENT_SECRET != '' }}"
          echo "SUPABASE_DATABASE_URL set?  ${{ secrets.SUPABASE_DATABASE_URL != '' }}"

      - name: Run ETL
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SUPABASE_DATABASE_URL: ${{ secrets.SUPABASE_DATABASE_URL }}
          TARGET: postgres
        run: python ETL/main.py
