name: Spotify ETL

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

env:
  TARGET: postgres

jobs:
  run-etl:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ETL
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: ETL/requirements.txt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Spotify ETL
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SUPABASE_DATABASE_URL: ${{ secrets.SUPABASE_DATABASE_URL }}
          SPOTIFY_PLAYLIST_IDS: ${{ secrets.SPOTIFY_PLAYLIST_IDS }}
        run: python -m ETL.main
